name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    name: Release Customer Pulse Survey Library
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Gradle (with caching)
        uses: gradle/actions/setup-gradle@v3

      - name: Grant Permission for Gradlew to Execute
        run: chmod +x gradlew

      # Build only the library module in release
      - name: Build AAR ⚙️🛠
        run: ./gradlew :CustomerPulseSurvey:assembleRelease --no-daemon --stacktrace

      # (Optional) show what was produced to help debug paths
      - name: List AAR outputs
        run: ls -l CustomerPulseSurvey/build/outputs/aar || true

      # Create (draft) release
      - name: Create Release ✅
        if: ${{ success() }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: true
          prerelease: false
          files: |
            CustomerPulseSurvey/build/outputs/aar/*release*.aar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      # If you also want to publish to GitHub Packages Maven later:
      # - name: Publish to GitHub Package Registry 🚀
      #   run: ./gradlew :CustomerPulseSurvey:publish --no-daemon --stacktrace
      #   env:
      #     GPR_USER: ${{ secrets.GPR_USER }}
      #     GPR_KEY:  ${{ secrets.GPR_KEY }}
